/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

#include <casadi/mem.h>
int rocket_aero_forces(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void rocket_aero_forces_incref(void);
void rocket_aero_forces_decref(void);
casadi_int rocket_aero_forces_n_out(void);
casadi_int rocket_aero_forces_n_in(void);
const char* rocket_aero_forces_name_in(casadi_int i);
const char* rocket_aero_forces_name_out(casadi_int i);
const casadi_int* rocket_aero_forces_sparsity_in(casadi_int i);
const casadi_int* rocket_aero_forces_sparsity_out(casadi_int i);
int rocket_aero_forces_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* rocket_aero_forces_functions(void);
int rocket_aero_moments(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void rocket_aero_moments_incref(void);
void rocket_aero_moments_decref(void);
casadi_int rocket_aero_moments_n_out(void);
casadi_int rocket_aero_moments_n_in(void);
const char* rocket_aero_moments_name_in(casadi_int i);
const char* rocket_aero_moments_name_out(casadi_int i);
const casadi_int* rocket_aero_moments_sparsity_in(casadi_int i);
const casadi_int* rocket_aero_moments_sparsity_out(casadi_int i);
int rocket_aero_moments_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* rocket_aero_moments_functions(void);
int rocket_prop_forces(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void rocket_prop_forces_incref(void);
void rocket_prop_forces_decref(void);
casadi_int rocket_prop_forces_n_out(void);
casadi_int rocket_prop_forces_n_in(void);
const char* rocket_prop_forces_name_in(casadi_int i);
const char* rocket_prop_forces_name_out(casadi_int i);
const casadi_int* rocket_prop_forces_sparsity_in(casadi_int i);
const casadi_int* rocket_prop_forces_sparsity_out(casadi_int i);
int rocket_prop_forces_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* rocket_prop_forces_functions(void);
int rocket_prop_moments(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void rocket_prop_moments_incref(void);
void rocket_prop_moments_decref(void);
casadi_int rocket_prop_moments_n_out(void);
casadi_int rocket_prop_moments_n_in(void);
const char* rocket_prop_moments_name_in(casadi_int i);
const char* rocket_prop_moments_name_out(casadi_int i);
const casadi_int* rocket_prop_moments_sparsity_in(casadi_int i);
const casadi_int* rocket_prop_moments_sparsity_out(casadi_int i);
int rocket_prop_moments_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* rocket_prop_moments_functions(void);
int quat2mrp(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void quat2mrp_incref(void);
void quat2mrp_decref(void);
casadi_int quat2mrp_n_out(void);
casadi_int quat2mrp_n_in(void);
const char* quat2mrp_name_in(casadi_int i);
const char* quat2mrp_name_out(casadi_int i);
const casadi_int* quat2mrp_sparsity_in(casadi_int i);
const casadi_int* quat2mrp_sparsity_out(casadi_int i);
int quat2mrp_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* quat2mrp_functions(void);
int quat2dcm(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void quat2dcm_incref(void);
void quat2dcm_decref(void);
casadi_int quat2dcm_n_out(void);
casadi_int quat2dcm_n_in(void);
const char* quat2dcm_name_in(casadi_int i);
const char* quat2dcm_name_out(casadi_int i);
const casadi_int* quat2dcm_sparsity_in(casadi_int i);
const casadi_int* quat2dcm_sparsity_out(casadi_int i);
int quat2dcm_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* quat2dcm_functions(void);
int tf_linvel(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void tf_linvel_incref(void);
void tf_linvel_decref(void);
casadi_int tf_linvel_n_out(void);
casadi_int tf_linvel_n_in(void);
const char* tf_linvel_name_in(casadi_int i);
const char* tf_linvel_name_out(casadi_int i);
const casadi_int* tf_linvel_sparsity_in(casadi_int i);
const casadi_int* tf_linvel_sparsity_out(casadi_int i);
int tf_linvel_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* tf_linvel_functions(void);
int tf_angvel(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, void* mem);
void tf_angvel_incref(void);
void tf_angvel_decref(void);
casadi_int tf_angvel_n_out(void);
casadi_int tf_angvel_n_in(void);
const char* tf_angvel_name_in(casadi_int i);
const char* tf_angvel_name_out(casadi_int i);
const casadi_int* tf_angvel_sparsity_in(casadi_int i);
const casadi_int* tf_angvel_sparsity_out(casadi_int i);
int tf_angvel_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w);
casadi_functions* tf_angvel_functions(void);
#ifdef __cplusplus
} /* extern "C" */
#endif
