/* This file was automatically generated by CasADi.
   The CasADi copyright holders make no ownership claim of its contents. */
#ifdef __cplusplus
extern "C" {
#endif

/* How to prefix internal symbols */
#ifdef CASADI_CODEGEN_PREFIX
  #define CASADI_NAMESPACE_CONCAT(NS, ID) _CASADI_NAMESPACE_CONCAT(NS, ID)
  #define _CASADI_NAMESPACE_CONCAT(NS, ID) NS ## ID
  #define CASADI_PREFIX(ID) CASADI_NAMESPACE_CONCAT(CODEGEN_PREFIX, ID)
#else
  #define CASADI_PREFIX(ID) jit_ ## ID
#endif

#include <math.h>

#ifndef casadi_real
#define casadi_real double
#endif

#ifndef casadi_int
#define casadi_int long long int
#endif

/* Add prefix to internal symbols */
#define casadi_f0 CASADI_PREFIX(f0)
#define casadi_s0 CASADI_PREFIX(s0)
#define casadi_s1 CASADI_PREFIX(s1)
#define casadi_s2 CASADI_PREFIX(s2)
#define casadi_sq CASADI_PREFIX(sq)

/* Symbol visibility in DLLs */
#ifndef CASADI_SYMBOL_EXPORT
  #if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
    #if defined(STATIC_LINKED)
      #define CASADI_SYMBOL_EXPORT
    #else
      #define CASADI_SYMBOL_EXPORT __declspec(dllexport)
    #endif
  #elif defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
    #define CASADI_SYMBOL_EXPORT __attribute__ ((visibility ("default")))
  #else
    #define CASADI_SYMBOL_EXPORT
  #endif
#endif

static const casadi_int casadi_s0[18] = {14, 1, 0, 14, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13};
static const casadi_int casadi_s1[8] = {4, 1, 0, 4, 0, 1, 2, 3};
static const casadi_int casadi_s2[20] = {16, 1, 0, 16, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15};

casadi_real casadi_sq(casadi_real x) { return x*x;}

/* rhs:(x[14],u[4],p[16])->(rhs[14]) */
static int casadi_f0(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem) {
  casadi_real a0, a1, a10, a11, a12, a13, a14, a15, a16, a17, a18, a19, a2, a20, a21, a22, a23, a24, a25, a26, a27, a28, a29, a3, a30, a31, a32, a33, a34, a35, a36, a37, a38, a39, a4, a40, a41, a42, a43, a44, a45, a46, a47, a48, a49, a5, a50, a51, a6, a7, a8, a9;
  a0=arg[2]? arg[2][3] : 0;
  a1=arg[2]? arg[2][2] : 0;
  a2=arg[0]? arg[0][13] : 0;
  a3=arg[2]? arg[2][15] : 0;
  a4=casadi_sq(a3);
  a4=(a2*a4);
  a1=(a1+a4);
  a4=(a0*a1);
  a5=arg[2]? arg[2][1] : 0;
  a3=casadi_sq(a3);
  a3=(a2*a3);
  a5=(a5+a3);
  a3=(a5*a0);
  a6=arg[2]? arg[2][4] : 0;
  a7=casadi_sq(a6);
  a3=(a3-a7);
  a3=(a1*a3);
  a4=(a4/a3);
  a7=1.0000000000000000e-03;
  a8=arg[0]? arg[0][7] : 0;
  a9=casadi_sq(a8);
  a10=arg[0]? arg[0][8] : 0;
  a11=casadi_sq(a10);
  a9=(a9+a11);
  a11=arg[0]? arg[0][9] : 0;
  a12=casadi_sq(a11);
  a9=(a9+a12);
  a9=sqrt(a9);
  a12=fabs(a9);
  a12=(a7<a12);
  a13=arg[2]? arg[2][7] : 0;
  a14=fabs(a8);
  a14=(a7<a14);
  a15=(a10/a8);
  a15=atan(a15);
  a15=(-a15);
  a14=(a14?a15:0);
  a15=fabs(a14);
  a16=4.0000000000000002e-01;
  a15=(a15<a16);
  a17=arg[2]? arg[2][9] : 0;
  a18=arg[2]? arg[2][8] : 0;
  a19=arg[1]? arg[1][1] : 0;
  a20=arg[1]? arg[1][3] : 0;
  a21=(a19-a20);
  a14=(a14+a21);
  a14=(a18*a14);
  a21=(a17+a14);
  a22=5.0000000000000000e-01;
  a23=arg[2]? arg[2][13] : 0;
  a22=(a22*a23);
  a23=casadi_sq(a8);
  a24=casadi_sq(a10);
  a23=(a23+a24);
  a24=casadi_sq(a11);
  a23=(a23+a24);
  a22=(a22*a23);
  a21=(a21*a22);
  a23=arg[2]? arg[2][12] : 0;
  a21=(a21*a23);
  a24=(a10/a9);
  a25=casadi_sq(a24);
  a26=(a8/a9);
  a27=casadi_sq(a26);
  a25=(a25+a27);
  a25=sqrt(a25);
  a27=fabs(a25);
  a27=(a7<a27);
  a28=(a26/a25);
  a28=(a27?a28:0);
  a29=(!a27);
  a30=1.;
  a29=(a29?a30:0);
  a28=(a28+a29);
  a28=(a21*a28);
  a28=(a15?a28:0);
  a29=arg[2]? arg[2][10] : 0;
  a31=arg[2]? arg[2][11] : 0;
  a14=casadi_sq(a14);
  a14=(a31*a14);
  a14=(a29+a14);
  a14=(a14*a22);
  a14=(a14*a23);
  a32=(a14*a24);
  a28=(a28-a32);
  a32=(a13*a28);
  a33=fabs(a8);
  a33=(a7<a33);
  a34=(a11/a8);
  a34=(-a34);
  a34=atan(a34);
  a34=(-a34);
  a33=(a33?a34:0);
  a34=fabs(a33);
  a34=(a34<a16);
  a35=arg[1]? arg[1][2] : 0;
  a36=(a19-a35);
  a33=(a33+a36);
  a33=(a18*a33);
  a36=(a17+a33);
  a36=(a36*a22);
  a36=(a36*a23);
  a37=(a11/a9);
  a38=casadi_sq(a37);
  a39=casadi_sq(a26);
  a38=(a38+a39);
  a38=sqrt(a38);
  a39=fabs(a38);
  a39=(a7<a39);
  a40=(a26/a38);
  a40=(-a40);
  a40=(a39?a40:0);
  a41=(!a39);
  a42=-1.;
  a41=(a41?a42:0);
  a40=(a40+a41);
  a40=(a36*a40);
  a40=(a34?a40:0);
  a33=casadi_sq(a33);
  a33=(a31*a33);
  a33=(a29+a33);
  a33=(a33*a22);
  a33=(a33*a23);
  a41=(a33*a37);
  a40=(a40-a41);
  a41=(a13*a40);
  a32=(a32-a41);
  a41=fabs(a8);
  a41=(a7<a41);
  a43=(a10/a8);
  a43=(-a43);
  a43=atan(a43);
  a43=(-a43);
  a41=(a41?a43:0);
  a43=fabs(a41);
  a43=(a43<a16);
  a20=(a19+a20);
  a41=(a41+a20);
  a41=(a18*a41);
  a20=(a17+a41);
  a20=(a20*a22);
  a20=(a20*a23);
  a44=casadi_sq(a24);
  a45=casadi_sq(a26);
  a44=(a44+a45);
  a44=sqrt(a44);
  a45=fabs(a44);
  a45=(a7<a45);
  a46=(a26/a44);
  a46=(-a46);
  a46=(a45?a46:0);
  a47=(!a45);
  a47=(a47?a42:0);
  a46=(a46+a47);
  a46=(a20*a46);
  a46=(a43?a46:0);
  a41=casadi_sq(a41);
  a41=(a31*a41);
  a41=(a29+a41);
  a41=(a41*a22);
  a41=(a41*a23);
  a47=(a41*a24);
  a46=(a46-a47);
  a47=(a13*a46);
  a32=(a32-a47);
  a47=fabs(a8);
  a47=(a7<a47);
  a42=(a11/a8);
  a42=atan(a42);
  a42=(-a42);
  a47=(a47?a42:0);
  a42=fabs(a47);
  a42=(a42<a16);
  a19=(a19+a35);
  a47=(a47+a19);
  a18=(a18*a47);
  a17=(a17+a18);
  a17=(a17*a22);
  a17=(a17*a23);
  a47=casadi_sq(a37);
  a19=casadi_sq(a26);
  a47=(a47+a19);
  a47=sqrt(a47);
  a19=fabs(a47);
  a19=(a7<a19);
  a35=(a26/a47);
  a35=(a19?a35:0);
  a16=(!a19);
  a16=(a16?a30:0);
  a35=(a35+a16);
  a35=(a17*a35);
  a35=(a42?a35:0);
  a18=casadi_sq(a18);
  a31=(a31*a18);
  a29=(a29+a31);
  a29=(a29*a22);
  a29=(a29*a23);
  a23=(a29*a37);
  a35=(a35-a23);
  a23=(a13*a35);
  a32=(a32+a23);
  a32=(a12?a32:0);
  a23=arg[0]? arg[0][1] : 0;
  a22=arg[0]? arg[0][0] : 0;
  a31=(a6*a22);
  a18=arg[0]? arg[0][2] : 0;
  a16=(a0*a18);
  a31=(a31+a16);
  a16=(a23*a31);
  a48=(a1*a23);
  a49=(a18*a48);
  a16=(a16-a49);
  a32=(a32-a16);
  a4=(a4*a32);
  a16=(a6*a1);
  a16=(a16/a3);
  a49=arg[2]? arg[2][6] : 0;
  a50=(a33*a24);
  a51=(a49*a50);
  a38=(a37/a38);
  a38=(a38*a36);
  a39=(a39?a38:0);
  a34=(a34?a39:0);
  a33=(a33*a26);
  a34=(a34-a33);
  a33=(a13*a34);
  a51=(a51+a33);
  a33=(a49*a28);
  a51=(a51-a33);
  a33=(a49*a46);
  a51=(a51-a33);
  a33=(a29*a24);
  a39=(a49*a33);
  a47=(a37/a47);
  a47=(a47*a17);
  a47=(-a47);
  a19=(a19?a47:0);
  a42=(a42?a19:0);
  a29=(a29*a26);
  a42=(a42-a29);
  a29=(a13*a42);
  a39=(a39-a29);
  a51=(a51+a39);
  a51=(a12?a51:0);
  a48=(a22*a48);
  a39=(a5*a22);
  a29=(a6*a18);
  a39=(a39+a29);
  a29=(a23*a39);
  a48=(a48-a29);
  a51=(a51-a48);
  a16=(a16*a51);
  a4=(a4-a16);
  if (res[0]!=0) res[0][0]=a4;
  a0=(a5*a0);
  a4=casadi_sq(a6);
  a0=(a0-a4);
  a0=(a0/a3);
  a4=(a49*a40);
  a25=(a24/a25);
  a25=(a25*a21);
  a25=(-a25);
  a27=(a27?a25:0);
  a15=(a15?a27:0);
  a27=(a14*a26);
  a15=(a15-a27);
  a27=(a13*a15);
  a14=(a14*a37);
  a25=(a49*a14);
  a27=(a27+a25);
  a4=(a4-a27);
  a24=(a24/a44);
  a24=(a24*a20);
  a45=(a45?a24:0);
  a43=(a43?a45:0);
  a26=(a41*a26);
  a43=(a43-a26);
  a13=(a13*a43);
  a41=(a41*a37);
  a37=(a49*a41);
  a13=(a13-a37);
  a4=(a4+a13);
  a49=(a49*a35);
  a4=(a4+a49);
  a12=(a12?a4:0);
  a39=(a18*a39);
  a31=(a22*a31);
  a39=(a39-a31);
  a12=(a12-a39);
  a0=(a0*a12);
  if (res[0]!=0) res[0][1]=a0;
  a5=(a5*a1);
  a5=(a5/a3);
  a5=(a5*a51);
  a6=(a6*a1);
  a6=(a6/a3);
  a6=(a6*a32);
  a5=(a5-a6);
  if (res[0]!=0) res[0][2]=a5;
  a5=2.5000000000000000e-01;
  a6=arg[0]? arg[0][3] : 0;
  a32=casadi_sq(a6);
  a3=arg[0]? arg[0][4] : 0;
  a1=casadi_sq(a3);
  a32=(a32+a1);
  a1=arg[0]? arg[0][5] : 0;
  a51=casadi_sq(a1);
  a32=(a32+a51);
  a32=(a30-a32);
  a51=2.;
  a0=casadi_sq(a6);
  a0=(a51*a0);
  a0=(a32+a0);
  a0=(a5*a0);
  a0=(a0*a22);
  a12=(a6*a3);
  a12=(a51*a12);
  a39=(a51*a1);
  a12=(a12-a39);
  a12=(a5*a12);
  a12=(a12*a23);
  a0=(a0+a12);
  a12=(a51*a3);
  a39=(a6*a1);
  a39=(a51*a39);
  a12=(a12+a39);
  a12=(a5*a12);
  a12=(a12*a18);
  a0=(a0+a12);
  if (res[0]!=0) res[0][3]=a0;
  a0=(a51*a1);
  a12=(a3*a6);
  a12=(a51*a12);
  a0=(a0+a12);
  a0=(a5*a0);
  a0=(a0*a22);
  a12=casadi_sq(a3);
  a12=(a51*a12);
  a12=(a32+a12);
  a12=(a5*a12);
  a12=(a12*a23);
  a0=(a0+a12);
  a12=(a3*a1);
  a12=(a51*a12);
  a39=(a51*a6);
  a12=(a12-a39);
  a12=(a5*a12);
  a12=(a12*a18);
  a0=(a0+a12);
  if (res[0]!=0) res[0][4]=a0;
  a0=(a1*a6);
  a0=(a51*a0);
  a12=(a51*a3);
  a0=(a0-a12);
  a0=(a5*a0);
  a0=(a0*a22);
  a12=(a51*a6);
  a39=(a1*a3);
  a39=(a51*a39);
  a12=(a12+a39);
  a12=(a5*a12);
  a12=(a12*a23);
  a0=(a0+a12);
  a12=casadi_sq(a1);
  a51=(a51*a12);
  a32=(a32+a51);
  a5=(a5*a32);
  a5=(a5*a18);
  a0=(a0+a5);
  if (res[0]!=0) res[0][5]=a0;
  a0=0.;
  if (res[0]!=0) res[0][6]=a0;
  a9=fabs(a9);
  a7=(a7<a9);
  a15=(a15+a34);
  a15=(a15+a43);
  a15=(a15+a42);
  a15=(a7?a15:0);
  a0=(a0<a2);
  a42=arg[1]? arg[1][0] : 0;
  a43=arg[2]? arg[2][5] : 0;
  a43=(a42*a43);
  a43=(a0?a43:0);
  a15=(a15+a43);
  a43=8.;
  a34=(a1*a6);
  a34=(a43*a34);
  a9=4.;
  a5=casadi_sq(a6);
  a32=casadi_sq(a3);
  a5=(a5+a32);
  a32=casadi_sq(a1);
  a5=(a5+a32);
  a32=(a30-a5);
  a9=(a9*a32);
  a32=(a9*a3);
  a34=(a34-a32);
  a5=(a30+a5);
  a5=casadi_sq(a5);
  a34=(a34/a5);
  a32=arg[2]? arg[2][14] : 0;
  a32=(a32+a2);
  a2=arg[2]? arg[2][0] : 0;
  a2=(a32*a2);
  a51=(a34*a2);
  a15=(a15+a51);
  a15=(a15/a32);
  a51=(a23*a11);
  a12=(a18*a10);
  a51=(a51-a12);
  a15=(a15-a51);
  if (res[0]!=0) res[0][7]=a15;
  a28=(a28-a50);
  a28=(a28+a46);
  a28=(a28-a33);
  a28=(a7?a28:0);
  a33=(a1*a3);
  a33=(a43*a33);
  a46=(a9*a6);
  a33=(a33+a46);
  a33=(a33/a5);
  a46=(a33*a2);
  a28=(a28+a46);
  a28=(a28/a32);
  a18=(a18*a8);
  a46=(a22*a11);
  a18=(a18-a46);
  a28=(a28-a18);
  if (res[0]!=0) res[0][8]=a28;
  a40=(a40-a14);
  a40=(a40-a41);
  a40=(a40+a35);
  a7=(a7?a40:0);
  a40=casadi_sq(a3);
  a35=casadi_sq(a6);
  a40=(a40+a35);
  a40=(a43*a40);
  a40=(a40/a5);
  a40=(a30-a40);
  a2=(a40*a2);
  a7=(a7+a2);
  a7=(a7/a32);
  a22=(a22*a10);
  a23=(a23*a8);
  a22=(a22-a23);
  a7=(a7-a22);
  if (res[0]!=0) res[0][9]=a7;
  a7=casadi_sq(a1);
  a22=casadi_sq(a3);
  a7=(a7+a22);
  a7=(a43*a7);
  a7=(a7/a5);
  a7=(a30-a7);
  a7=(a7*a8);
  a22=(a6*a3);
  a22=(a43*a22);
  a23=(a9*a1);
  a22=(a22-a23);
  a22=(a22/a5);
  a22=(a22*a10);
  a7=(a7+a22);
  a22=(a6*a1);
  a22=(a43*a22);
  a23=(a9*a3);
  a22=(a22+a23);
  a22=(a22/a5);
  a22=(a22*a11);
  a7=(a7+a22);
  if (res[0]!=0) res[0][10]=a7;
  a7=(a3*a6);
  a7=(a43*a7);
  a22=(a9*a1);
  a7=(a7+a22);
  a7=(a7/a5);
  a7=(a7*a8);
  a22=casadi_sq(a1);
  a23=casadi_sq(a6);
  a22=(a22+a23);
  a22=(a43*a22);
  a22=(a22/a5);
  a30=(a30-a22);
  a30=(a30*a10);
  a7=(a7+a30);
  a3=(a3*a1);
  a43=(a43*a3);
  a9=(a9*a6);
  a43=(a43-a9);
  a43=(a43/a5);
  a43=(a43*a11);
  a7=(a7+a43);
  if (res[0]!=0) res[0][11]=a7;
  a34=(a34*a8);
  a33=(a33*a10);
  a34=(a34+a33);
  a40=(a40*a11);
  a34=(a34+a40);
  if (res[0]!=0) res[0][12]=a34;
  a0=(a0?a42:0);
  a0=(-a0);
  if (res[0]!=0) res[0][13]=a0;
  return 0;
}

CASADI_SYMBOL_EXPORT int rhs(const casadi_real** arg, casadi_real** res, casadi_int* iw, casadi_real* w, int mem){
  return casadi_f0(arg, res, iw, w, mem);
}

CASADI_SYMBOL_EXPORT int rhs_alloc_mem(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT int rhs_init_mem(int mem) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rhs_free_mem(int mem) {
}

CASADI_SYMBOL_EXPORT int rhs_checkout(void) {
  return 0;
}

CASADI_SYMBOL_EXPORT void rhs_release(int mem) {
}

CASADI_SYMBOL_EXPORT void rhs_incref(void) {
}

CASADI_SYMBOL_EXPORT void rhs_decref(void) {
}

CASADI_SYMBOL_EXPORT casadi_int rhs_n_in(void) { return 3;}

CASADI_SYMBOL_EXPORT casadi_int rhs_n_out(void) { return 1;}

CASADI_SYMBOL_EXPORT casadi_real rhs_default_in(casadi_int i){
  switch (i) {
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rhs_name_in(casadi_int i){
  switch (i) {
    case 0: return "x";
    case 1: return "u";
    case 2: return "p";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const char* rhs_name_out(casadi_int i){
  switch (i) {
    case 0: return "rhs";
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rhs_sparsity_in(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    case 1: return casadi_s1;
    case 2: return casadi_s2;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT const casadi_int* rhs_sparsity_out(casadi_int i) {
  switch (i) {
    case 0: return casadi_s0;
    default: return 0;
  }
}

CASADI_SYMBOL_EXPORT int rhs_work(casadi_int *sz_arg, casadi_int* sz_res, casadi_int *sz_iw, casadi_int *sz_w) {
  if (sz_arg) *sz_arg = 3;
  if (sz_res) *sz_res = 1;
  if (sz_iw) *sz_iw = 0;
  if (sz_w) *sz_w = 0;
  return 0;
}


#ifdef __cplusplus
} /* extern "C" */
#endif
